repository_type: pipeline

nf_core_version: 4.0.2

lint:
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-panannotator_logo_light.png
    - docs/images/nf-core-panannotator_logo_light.png
    - docs/images/nf-core-panannotator_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/linting.yml
    - .github/workflows/linting_comment.yml
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
  container_configs: false
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-panannotator_logo_light.png
    - docs/images/nf-core-panannotator_logo_light.png
    - docs/images/nf-core-panannotator_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/test_full.config

template:
  org: LABGeM
  name: panAnnotator
  description: PANFAM clustering and annotation workflow for PanGBank pangenome family
    representatives
  author: Yazid Hoblos
  version: 0.1.0
  force: true
  outdir: active/panAnnotator
  is_nfcore: false
