name: Run nf-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "**/meta.yml"
      - "**/*.md"
      - "**/*.png"
      - "**/*.svg"
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NXF_ANSI_LOG: false
  NFT_VER: "0.9.4"
  NFT_WORKDIR: "/tmp/nf-test"
  NXF_CONDA_CACHEDIR: "/tmp/nextflow-conda"
  NXF_SINGULARITY_CACHEDIR: "/tmp/nextflow-singularity"

jobs:
  nf-test:
    name: ${{ matrix.profile }} | ${{ matrix.NXF_VER }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        NXF_VER: ["25.10.4", "latest-everything"]
        profile: ["conda"]

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: recursive

      - name: Run nf-test
        uses: ./.github/actions/nf-test
        env:
          NXF_VERSION: ${{ matrix.NXF_VER }}
        with:
          profile: ${{ matrix.profile }}
          shard: 1
          total_shards: 1
          paths: tests/default.nf.test
          tags: pipeline
